# Generated by Django 2.1.3 on 2019-05-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=100, unique=True, verbose_name='书名')),
                ('cate', models.CharField(choices=[('0', '社科'), ('1', '文艺'), ('2', '经济'), ('3', '法律'), ('4', '古籍'), ('5', '艺术'), ('6', '科技'), ('7', '计算机'), ('8', '医药卫生'), ('9', '生活'), ('10', '建筑'), ('11', '少儿'), ('12', '教辅'), ('13', '外文'), ('14', '音像'), ('15', '音乐'), ('16', '杂志')], default=0, max_length=10, verbose_name='分类')),
                ('zuozhe', models.CharField(max_length=20, verbose_name='作者')),
                ('chubanshe', models.CharField(max_length=20, verbose_name='出版社')),
                ('num', models.PositiveIntegerField(max_length=20, verbose_name='数量')),
                ('weizhi', models.CharField(default='', max_length=30, verbose_name='位置')),
                ('c_time', models.DateTimeField(verbose_name='入库时间')),
            ],
            options={
                'verbose_name_plural': '图书信息',
            },
        ),
        migrations.CreateModel(
            name='Gonggao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100, verbose_name='内容')),
                ('c_time', models.DateTimeField(verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '公告',
            },
        ),
        migrations.CreateModel(
            name='HuanInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=10, verbose_name='用户名')),
                ('book_name', models.CharField(max_length=10, verbose_name='书名')),
                ('c_time', models.CharField(max_length=10, verbose_name='借书日期')),
                ('j_time', models.CharField(max_length=10, verbose_name='借书期限')),
                ('h_time', models.CharField(default='', max_length=10, verbose_name='规定还书日期')),
                ('h_date', models.CharField(default='', max_length=10, verbose_name='借书人还书的日期')),
                ('book_num', models.CharField(default='', max_length=10, verbose_name='还书数量')),
                ('f_book_num', models.CharField(default='', max_length=10, verbose_name='还书后的库存')),
            ],
            options={
                'verbose_name_plural': '还书情况',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
            ],
            options={
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='JieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=10, verbose_name='用户名')),
                ('book_name', models.CharField(max_length=10, verbose_name='书名')),
                ('c_time', models.CharField(max_length=10, verbose_name='借书时间')),
                ('j_time', models.CharField(max_length=10, verbose_name='借书期限')),
                ('h_time', models.CharField(default='', max_length=10, verbose_name='规定还书日期')),
                ('book_num', models.CharField(default='', max_length=10, verbose_name='借书数量')),
                ('f_book_num', models.CharField(default='', max_length=10, verbose_name='借书后的库存')),
            ],
            options={
                'verbose_name_plural': '借阅情况',
            },
        ),
        migrations.CreateModel(
            name='liuyan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=10, verbose_name='用户名')),
                ('c_time', models.CharField(max_length=20, verbose_name='创建时间')),
                ('content', models.CharField(max_length=100, verbose_name='留言内容')),
            ],
            options={
                'verbose_name_plural': '留言',
            },
        ),
    ]
